### PR TITLE
Bump ansible dependencies

### PR DESCRIPTION
**Pull request by joshmoore**
Attempts a migration to ansible 2.3 across the currently passing roles.

### CODE REVIEW

**Comment by joshmoore** [comment]
All (currently active) tests passed with ansible 2.3. Not exactly sure what we want to do with this PR.

**Comment by manics** [comment]
Merge and tag it? If any other repos use `ome-ansible-molecule-dependencies` and break they can pin to the previous version. Alternatively modify all `ansible-role-*/.travis.yml` files to run molecule test with two versions of `ome-ansible-molecule-dependencies`, the tagged version corresponding to Ansible 2.2 and this one for 2.3? Could also decide to name the tags on this repo based on the major.minor ansible version for ease of use?

**Comment by joshmoore** [comment]
So, this repo is currently at 0.1.0. So choices are:

 * A) hold off until Ansible 2.2 is dropped
 * B) teach this repo to test 2.2 & 2.3, keeping 2.2
 * C) B but keeping 2.3
 * D) merge and tag as 0.2.0
 * E) merge and tag as 2.3.0

Think my preference is D. 


> Alternatively modify all ansible-role-*/.travis.yml files to

In general, I've been hoping this repo would prevent us from *needing* to update all dependent repos.

**Comment by sbesson** [comment]
One additional thought (although probably too late), is that this is slowly turning this repo in somethink more general like `ome-ansible-base` i.e. a meta package providing the base Ansible requirements used within the team.

A related thought is that https://github.com/openmicroscopy/infrastructure/blob/master/requirements.txt could probably be updated to install Ansible via `ome-ansible-molecule-dependencies==x.y.z` so that we are consistent.

Regarding the various options, as discussed this morning, most of the @openmicroscopy/devops team is effectively already using Ansible 2.3 or switching to it, so I would vote for either C or D to make sure our roles are tested against our recommended/production prerequisites. If we assume deprecating/dropping Ansible 2.2 in the upcoming months is not going to be problematic, we could certainly go for option D.

**Comment by joshmoore** [comment]
> ome-ansible-base i.e. a meta package providing the base Ansible requirements used within the team.

Something else I'm realizing that is often copied-n-pasted are the tests. If we could import standard OME tests, it'd save a good deal of boilerplate. Or at least the fixtures, see

http://www.axelspringerideas.de/blog/index.php/2016/08/16/continuously-delivering-infrastructure-part-1-ansible-molecule-and-testinfra/

**Comment by joshmoore** [comment]
Moved my idea about the tests to #6. I'm still happy with D. If there are not objections, I can either merge and push today, or leave you guys to do it (so that I don't leave anyone with a mess).

**Comment by manics** [comment]
I vote for merging and tagging `0.2.0`

**Comment by joshmoore** [comment]
Cheers all. Releasing as 0.2.0 then.

**Comment by joshmoore** [comment]
Released with: `twine upload dist/...tar.gz`

https://pypi.python.org/pypi/ome-ansible-molecule-dependencies/0.2.0

Note: required `pip install -U setuptools` due to weirdness with testinfra.

**Pull request merged**
