### PR TITLE
Test all openmicroscopy galaxy roles

### PR DESCRIPTION
**Pull request by manics**
This is an attempt to test all openmicroscopy Ansible Galaxy roles.

In future this will allow bumps in ome-ansible-molecule-dependencies to be tested.

### CODE REVIEW

**Comment by joshmoore** [comment]
Note sure if there's any overlap, but have you seen https://github.com/nickjj/ansigenome#example-rebuild-output ?

**Comment by manics** [comment]
First time I've seen that.

**Comment by joshmoore** [comment]
No objections in chat. Merging (untagged). I may try to open a few more tests against this repo for sanity checking, before trying a merge-strategy on jenkins.

**Comment by joshmoore** [comment]
No objections in chat. Merging (untagged). I may try to open a few more tests against this repo for sanity checking, before trying a merge-strategy on jenkins.

**Pull request merged**
