### PR TITLE
Ansible 2.8.18 molecule 2.22 python 3.6

### PR DESCRIPTION
**Pull request by manics**
Update to Ansible 2.~9~8 and Molecule 2.22 (the last version before the recently released 3.0).
These are the versions that happen to be in conda-forge right now.

In conjunction with https://github.com/ome/ome-ansible-molecule/pull/19 this could be released as `0.5.0`

### CODE REVIEW

**Comment by sbesson** [comment]
Overall, I am in favor of initiating the work to bump our production version of Ansible to a more recent version. Primary questions are about the roadmap and the next steps to get there:

- testing: with the current infrastructure, https://github.com/ome/ansible-roles/issues/13 will need to be tackled to have a this change successfully tested against as many production Ansible roles as possible  - see https://travis-ci.org/snoopycrimecop/ansible-roles/builds/658494731 for the nightly run. 
- version: is `ome-ansible-molecule 0.5.0` the next target together with the Python 3 change in #19 ? In this case, the README as well as all places in our codebase capping this package will need to be reviewed.

**Comment by manics** [comment]
In the short term I'd consider supporting both `0.4.0` (Ansible 2.6) and `0.5.0` (Ansible 2.9) in the main public roles (omero-web, omero-server, and dependencies). Since we'll soon have support for two operating systems in those roles we can test one OS with `0.4.0` and the other with `0.5.0` in the travis matrix

**Comment by sbesson** [comment]
See https://travis-ci.org/github/snoopycrimecop/ansible-roles/builds/663321803 for the first Travis build effectively testing the impact of this proposed change across our Ansible roles. Looking quickly at them, many of the failures seem to be syntactic or related to deprecated features.

I am unclear how the dual version testing would work both at the level of individual roles as well as in `ansible-roles` but happy to read more about that. Additionally, if we don't feel like committing to a full `0.5.0` but want to gain some more experience, we could always create a `0.5.0.dev0` pre-release and start consuming it.

**Comment by manics** [comment]
I think it's fine to commit to `0.5.0`. For dual version testing I'd restrict it to just the main user-facing roles, i.e. test _one_ scenario in each of omero-server and omero-web using `0.4.0`, and use the new `0.5.0` for all other tests and roles including this repo. This provides a basic test of backwards compatibility so we're not forcing users of our main roles to immediately upgrade, whilst emphasizing that the OME is moving to Ansible 2.9.

For a role-level example see https://github.com/ome/ansible-role-python3-virtualenv/blob/0.1.1/.travis.yml#L8-L17 (this was required to test a _remote_ Python 3 environment, Ansible 2.6 has bugs)

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [ANSIBLE-ROLES-merge#1016](https://ci.openmicroscopy.org/job/ANSIBLE-ROLES-merge/1016/). See the [console output](https://ci.openmicroscopy.org/job/ANSIBLE-ROLES-merge/1016/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - setup.py

~~--conflicts~~ Conflict resolved in build [ANSIBLE-ROLES-merge#1124](https://ci.openmicroscopy.org/job/ANSIBLE-ROLES-merge/1124/). See the [console output](https://ci.openmicroscopy.org/job/ANSIBLE-ROLES-merge/1124/consoleText) for more details.

**Comment by manics** [comment]
See https://github.com/ome/ansible-roles/pull/27 for the results

**Comment by sbesson** [comment]
Given the number of places which are starting to hardcode more recent Ansible versions (https://github.com/ome/ansible-role-ice/pull/13, https://github.com/ome/ansible-role-python3-virtualenv/commit/11af8c8993c8f7e783d01deed9cbbf4095e9efb5), is this something we should start pushing once/while the Ansible role GitHub Actions migration is sorted?

https://github.com/ome/ansible-roles/pull/27 suggested the impact on the roles/playbooks might be fairly minor. Is there a way to pre-test a new ome-ansible-molecule version which does not involve opening N PRs against each Ansible repo?

**Comment by manics** [comment]
Maybe add a modified version of https://github.com/ome/action-ansible-molecule-list-scenarios to find all `submodule/molecule/*` scenarios, then run the molecule tests in a second matrix job in this repo?

**Comment by sbesson** [comment]
One additional question: in all the places mentioned in https://github.com/ome/ome-ansible-molecule/pull/20#issuecomment-756708051, you have used Ansible 2.8. Is this a safer version increment if you have already gained experience with it?

**Comment by manics** [comment]
I used 2.8 because it's what I've been using for ages. The reason for choosing 2.9 here is it's more recent, which means we can put off the next upgrade for slightly longer 😄, but as you say no-one's used it for daily use yet.

**Comment by sbesson** [comment]
If you have already extensive deployment experience with Ansible 2.8, my vote would be to update this PR to capture the version you have been using and getting this released as `0.5.0` (or `rc1` if we think it is safer). /cc @joshmoore 

I can look into getting the roles tested with this major version while keeping in mind the need to easily test new Ansible versions given the velocity of the Ansible project.

**Comment by manics** [comment]
I can switch to 2.8 if that's the consensus.

Is it required that we test all roles before bumping the version of Ansible? It seems like unnecessary coupling and I suspect it's one of the reasons the ansible version here never gets bumped- whoever bumps it has to take on the responsibility of fixing all roles.

https://github.com/ome/action-ome-ansible-molecule has no tags, but if we add semver tags to it we could instead upgrade roles one at a time.

**Comment by sbesson** [comment]
> Is it required that we test all roles before bumping the version of Ansible? It seems like unnecessary coupling and I suspect it's one of the reasons the ansible version here never gets bumped- whoever bumps it has to take on the responsibility of fixing all roles.

I agree about the downsides about such strong coupling and moving towards a more faster lifecycle would be beneficial for the reasons you are mentioning.

> I can switch to 2.8 if that's the consensus.

For me the main advantage of creating an intermediate state with Ansible 2.8 is that you have already established it is working with all our playbooks. 

> https://github.com/ome/action-ome-ansible-molecule has no tags, but if we add semver tags to it we could instead upgrade roles one at a time.

With regards to testing, I think this is the reason why we had previously `pip install "ome-ansible-molecule<0.5"` in Travis CI configuration and `~/venv/bin/pip install "ome-ansible-molecule==0.4.*"` in the OME Molecule action. My expectation is that it should ensure roles are all tested with a defined Ansible version while we are bumping this meta-package for preliminary testing.

Tagging the action would make sense for upgrading the CI across all Ansible roles & playbooks. Alternatively/in addition, I was considering extending the role to support an environment variable e.g. `OME_ANSIBLE_MOLECULE_VERSION` that could be overridden at the repo/organization level

**Comment by manics** [comment]
I've updated this to Ansible 2.8.18 (the last in the 2.8 series)

**Comment by sbesson** [comment]
Thanks. As discussed today, merging and tagging as `0.5.0`. I will look into testing it first against the various playbooks then against the roles.

**Review by sbesson — APPROVED** [review]

**Pull request merged**
